/**
 * İçerik haritası — teknik i18n anahtarlarını GERÇEK SAYFA + BÖLÜM yapısına
 * eşler. Amaç: teknik olmayan site sahibi "imm.les_p2Text" gibi kriptik bir
 * anahtar yerine "Türkçe Ders → Süreç → 2. adım metni" gibi anlaşılır bir
 * yerden düzenlesin.
 *
 * - Sayfalar, sitedeki menü/görünüm sırasıyla dizilidir.
 * - Her sayfanın bölümleri, sayfada yukarıdan aşağıya göründükleri sırayla.
 * - `keys` = messages/tr.json içindeki NOKTA ile düzleştirilmiş tam anahtarlar
 *   (örn. namespace `home` + anahtar `heroTitle` → "home.heroTitle").
 * - Haritada olmayan anahtarlar editörde otomatik "Diğer" bölümüne düşer;
 *   burada görünür ve düzenlenmesi muhtemel ana metinler kapsanır.
 */

export type ContentSection = { title: string; help?: string; keys: string[] };
export type ContentPageDef = {
  id: string;
  label: string;
  description?: string;
  sections: ContentSection[];
};

export const CONTENT_PAGES: ContentPageDef[] = [
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "home",
    label: "Anasayfa",
    description: "Sitenin giriş sayfası — hero, hizmetler, oteller, rotalar ve kapanış.",
    sections: [
      {
        title: "Hero / üst bölüm",
        help: "Sayfanın en tepesindeki büyük başlık, alt metin ve butonlar.",
        keys: [
          "home.heroTitle",
          "home.heroSubtitle",
          "home.heroDiff",
          "home.heroProof1",
          "home.heroProof2",
          "home.heroProof3",
          "home.heroProof4",
          "home.heroCtaPrimary",
          "home.heroCtaSecondary",
          "home.diveDeep",
          "home.scrollCue",
          "home.soundWave",
        ],
      },
      {
        title: "Fark şeridi (hero altı kimlik cümlesi)",
        help: "Hero'nun hemen altındaki kimlik cümlesi + mikro-kanıt rozetleri.",
        keys: ["home.diffLine", "home.diffHuman"],
      },
      {
        title: "Hizmetler / nasıl yardımcı oluyoruz",
        keys: ["home.servicesTitle", "home.servicesSubtitle"],
      },
      {
        title: "Antalya'da seni neler bekliyor (aktiviteler)",
        keys: [
          "home.actTitle",
          "home.actScuba",
          "home.actBoat",
          "home.actSports",
          "home.actHotels",
        ],
      },
      {
        title: "Antalya'nın incileri / Land of Legends",
        help: "Öne çıkan yerler ve tema parkı tanıtımı.",
        keys: [
          "home.placesTitle",
          "home.lolDesc",
          "imm.lol_eyebrow",
          "imm.lol_watch",
          "imm.lol_h1",
          "imm.lol_h2",
          "imm.lol_h3",
          "imm.lol_h4",
          "imm.lol_takeYou",
        ],
      },
      {
        title: "Oteller",
        help: "Anasayfadaki öne çıkan otel kartları başlığı (otel metinleri için 'Antalya Danışmanlık → Oteller' bölümüne bakın).",
        keys: ["home.hotelsEyebrow", "home.hotelsTitle", "home.hotelsNote", "home.hotelsCta"],
      },
      {
        title: "Neden biz",
        keys: [
          "home.whyTitle",
          "home.why1Title",
          "home.why1Text",
          "home.why2Title",
          "home.why2Text",
          "home.why3Title",
          "home.why3Text",
        ],
      },
      {
        title: "Sana özel plan formu",
        help: "Kişiye özel tatil planı isteme formunun tüm etiketleri, seçenekleri ve mesaj şablonu.",
        keys: [
          "home.ctaTitle",
          "home.ctaText",
          "home.ctaCta",
          "plan.eyebrow",
          "plan.title",
          "plan.subtitle",
          "plan.fArrival",
          "plan.fPeople",
          "plan.fDays",
          "plan.fBudget",
          "plan.fStyle",
          "plan.fContact",
          "plan.fHandle",
          "plan.fHandlePh",
          "plan.fNote",
          "plan.fNotePh",
          "plan.styleFamily",
          "plan.styleRomantic",
          "plan.styleLuxury",
          "plan.styleAdventure",
          "plan.styleBeach",
          "plan.budgetEco",
          "plan.budgetMid",
          "plan.budgetLux",
          "plan.budgetUltra",
          "plan.contactWa",
          "plan.contactTg",
          "plan.cta",
          "plan.note",
          "plan.msgIntro",
          "plan.msgArrival",
          "plan.msgPeople",
          "plan.msgDays",
          "plan.msgBudget",
          "plan.msgStyle",
          "plan.msgHandle",
          "plan.msgNote",
        ],
      },
      {
        title: "Türkçe ders + PetLingo tanıtımı",
        help: "Anasayfada Türkçe ders hizmetini tanıtan bölüm.",
        keys: [
          "lessonsHome.eyebrow",
          "lessonsHome.title",
          "lessonsHome.text",
          "lessonsHome.c1",
          "lessonsHome.c2",
          "lessonsHome.c3",
          "lessonsHome.bonusBadge",
          "lessonsHome.petlingoText",
          "lessonsHome.cta",
        ],
      },
      {
        title: "Türkiye'de eğitim tanıtımı",
        help: "Anasayfada eğitim danışmanlığını tanıtan bölüm.",
        keys: [
          "studyHome.eyebrow",
          "studyHome.title",
          "studyHome.text",
          "studyHome.f1",
          "studyHome.f2",
          "studyHome.f3",
          "studyHome.f4",
          "studyHome.cta",
        ],
      },
      {
        title: "Misafir sözleri (yorumlar)",
        keys: [
          "voices.eyebrow",
          "voices.title",
          "voices.honest",
          "voices.emptyTitle",
          "voices.emptyText",
          "voices.serve",
          "voices.cta",
        ],
      },
      {
        title: "Ödeme & güven",
        keys: [
          "trust.eyebrow",
          "trust.title",
          "trust.body",
          "trust.p1",
          "trust.p2",
          "trust.p3",
          "trust.p4",
          "trust.p5",
        ],
      },
      {
        title: "Mini SSS",
        help: "Anasayfa altındaki kısa soru-cevap. Tam metinler 'SSS' sayfasındakiyle aynı anahtarları kullanır.",
        keys: ["imm.faq_eyebrow"],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "antalya",
    label: "Antalya Danışmanlık",
    description: "Menüdeki 'Antalya Danışmanlık' (/antalya) sayfası — hazır rotalar ve oteller.",
    sections: [
      {
        title: "Hero / üst bölüm",
        keys: ["antalya.title", "antalya.intro"],
      },
      {
        title: "Öne çıkanlar (özellikler)",
        keys: [
          "antalya.feature1",
          "antalya.feature2",
          "antalya.feature3",
          "antalya.feature4",
          "antalya.cta",
        ],
      },
      {
        title: "Antalya tanıtım bölümleri",
        help: "Bölgeler, sokakta yürü (360°) ve kapanış tanıtım metinleri.",
        keys: [
          "imm.ant_introEyebrow",
          "imm.ant_introTitle",
          "imm.ant_introText",
          "imm.ant_regionsEyebrow",
          "imm.ant_regionsTitle",
          "imm.ant_streetEyebrow",
          "imm.ant_streetTitle",
          "imm.ant_streetIntro",
          "imm.ant_streetHint",
          "imm.ant_ctaTitle",
          "imm.ant_ctaText",
        ],
      },
      {
        title: "Hazır rotalar / paketler — başlıklar & etiketler",
        help: "Paket vitrininin başlığı ve kart etiketleri (dahiller, gün, en uygun kime, buton yazıları).",
        keys: [
          "routes.eyebrow",
          "routes.title",
          "routes.subtitle",
          "routes.promise",
          "routes.daysWord",
          "routes.dayLabel",
          "routes.included",
          "routes.flightsNote",
          "routes.bestForLabel",
          "routes.cta",
          "routes.custom",
          "routes.curated",
          "routes.routeLabel",
          "routes.allInLabel",
          "routes.ctaPick",
          "routes.oneMessage",
          "routes.details",
          "routes.close",
          "routes.dayByDay",
          "routes.priceLabel",
          "routes.whyHotel",
          "routes.mapTitle",
          "routes.waMsg",
          "routes.tgPick",
          "routes.tgCopied",
          "routes.emailPick",
          "routes.aud_classic",
          "routes.aud_honeymoon",
          "routes.aud_family",
          "routes.aud_luxury",
        ],
      },
      {
        title: "Rota adımları — ortak (uçuş / transfer / giriş)",
        keys: [
          "routes.st_flight_t",
          "routes.st_flight_d",
          "routes.st_transfer_t",
          "routes.st_transfer_d",
          "routes.st_checkin_t",
        ],
      },
      {
        title: "Rota 1 — Lara Barut (3 gün)",
        keys: [
          "routes.r1_name",
          "routes.r1_tag",
          "routes.r1_best",
          "routes.r1_ck",
          "routes.r1_s1_t",
          "routes.r1_s1_d",
          "routes.r1_s2_t",
          "routes.r1_s2_d",
          "routes.r1_s3_t",
          "routes.r1_s3_d",
        ],
      },
      {
        title: "Rota 2 — Cullinan Belek (5 gün)",
        keys: [
          "routes.r2_name",
          "routes.r2_tag",
          "routes.r2_best",
          "routes.r2_ck",
          "routes.r2_s1_t",
          "routes.r2_s1_d",
          "routes.r2_s2_t",
          "routes.r2_s2_d",
          "routes.r2_s3_t",
          "routes.r2_s3_d",
          "routes.r2_s4_t",
          "routes.r2_s4_d",
        ],
      },
      {
        title: "Rota 3 — NG Phaselis Bay (balayı, 5 gün)",
        keys: [
          "routes.r3_name",
          "routes.r3_tag",
          "routes.r3_best",
          "routes.r3_ck",
          "routes.r3_s1_t",
          "routes.r3_s1_d",
          "routes.r3_s2_t",
          "routes.r3_s2_d",
          "routes.r3_s3_t",
          "routes.r3_s3_d",
          "routes.r3_s4_t",
          "routes.r3_s4_d",
        ],
      },
      {
        title: "Rota 4 — Land of Legends (aile, 7 gün)",
        keys: [
          "routes.r4_name",
          "routes.r4_tag",
          "routes.r4_best",
          "routes.r4_ck",
          "routes.r4_s1_t",
          "routes.r4_s1_d",
          "routes.r4_s2_t",
          "routes.r4_s2_d",
          "routes.r4_s3_t",
          "routes.r4_s3_d",
          "routes.r4_s4_t",
          "routes.r4_s4_d",
          "routes.r4_s5_t",
          "routes.r4_s5_d",
          "routes.r4_s6_t",
          "routes.r4_s6_d",
        ],
      },
      {
        title: "Rota 5 — Maxx Royal Kemer (lüks, 7 gün)",
        keys: [
          "routes.r5_name",
          "routes.r5_tag",
          "routes.r5_best",
          "routes.r5_ck",
          "routes.r5_s1_t",
          "routes.r5_s1_d",
          "routes.r5_s2_t",
          "routes.r5_s2_d",
          "routes.r5_s3_t",
          "routes.r5_s3_d",
          "routes.r5_s4_t",
          "routes.r5_s4_d",
          "routes.r5_s5_t",
          "routes.r5_s5_d",
          "routes.r5_s6_t",
          "routes.r5_s6_d",
        ],
      },
      {
        title: "Rota dahilleri & ek hizmetler",
        help: "Her pakete dahil olanlar ve isteğe bağlı ek hizmetler (tekne, spa, VIP...).",
        keys: [
          "routes.allInLabel",
          "routes.inc_flight",
          "routes.inc_transfer",
          "routes.inc_hotel",
          "routes.inc_board",
          "routes.inc_tours",
          "routes.inc_support",
          "routes.a_boat",
          "routes.a_spa",
          "routes.a_guide",
          "routes.a_vip",
          "routes.a_night",
          "routes.a_dinner",
          "routes.custTitle",
          "routes.custHint",
          "routes.addonsTitle",
          "routes.addNotePh",
          "routes.mIntro2",
          "routes.mKept",
          "routes.mRemoved",
          "routes.mAddons",
          "routes.mNote",
        ],
      },
      {
        title: "Rota — itiraz giderme (endişeler)",
        keys: [
          "routes.worryLead",
          "routes.worry1",
          "routes.worry2",
          "routes.worry3",
          "routes.worry4",
          "routes.worryResolved",
        ],
      },
      {
        title: "Oteller",
        help: "Öne çıkan otellerin konum / kime uygun / neden / not metinleri. Ortak etiketler ilk üç anahtar.",
        keys: [
          "hotelsd.bestFor",
          "hotelsd.why",
          "hotelsd.note",
          "hotelsd.waAsk",
          "hotelsd.waMsg",
          "hotelsd.tgAsk",
          "hotelsd.emailAsk",
          "hotelsd.cullinan_loc",
          "hotelsd.cullinan_best",
          "hotelsd.cullinan_why",
          "hotelsd.cullinan_note",
          "hotelsd.maxxbelek_loc",
          "hotelsd.maxxbelek_best",
          "hotelsd.maxxbelek_why",
          "hotelsd.maxxbelek_note",
          "hotelsd.regnum_loc",
          "hotelsd.regnum_best",
          "hotelsd.regnum_why",
          "hotelsd.regnum_note",
          "hotelsd.maxxkemer_loc",
          "hotelsd.maxxkemer_best",
          "hotelsd.maxxkemer_why",
          "hotelsd.maxxkemer_note",
          "hotelsd.ngphaselis_loc",
          "hotelsd.ngphaselis_best",
          "hotelsd.ngphaselis_why",
          "hotelsd.ngphaselis_note",
          "hotelsd.larabarut_loc",
          "hotelsd.larabarut_best",
          "hotelsd.larabarut_why",
          "hotelsd.larabarut_note",
          "hotelsd.bayou_loc",
          "hotelsd.bayou_best",
          "hotelsd.bayou_why",
          "hotelsd.bayou_note",
          "hotelsd.legends_loc",
          "hotelsd.legends_best",
          "hotelsd.legends_why",
          "hotelsd.legends_note",
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "lessons",
    label: "Türkçe Ders",
    description: "Online Türkçe ders sayfası — süreç, öğretmen, PetLingo ve rezervasyon.",
    sections: [
      {
        title: "Hero / üst bölüm",
        keys: ["lessons.title", "lessons.intro"],
      },
      {
        title: "Öğrenme süreci (nasıl öğreniyorsun)",
        help: "Seviye tespiti → canlı ders → günlük pratik → ilerleme adımları.",
        keys: [
          "imm.les_processEyebrow",
          "imm.les_processTitle",
          "imm.les_processDesc",
          "imm.les_p1Title",
          "imm.les_p1Text",
          "imm.les_p2Title",
          "imm.les_p2Text",
          "imm.les_p3Title",
          "imm.les_p3Text",
          "imm.les_p4Title",
          "imm.les_p4Text",
        ],
      },
      {
        title: "Öğretmen tanıtımı",
        keys: [
          "imm.les_teacher_eyebrow",
          "imm.les_teacher_title",
          "imm.les_teacher_text",
          "imm.les_cred1",
          "imm.les_cred2",
          "imm.les_cred3",
          "imm.les_cred4",
        ],
      },
      {
        title: "0'dan C2'ye seviye yolu",
        help: "Seviye rozetleri ve hangi seviyede olduğunuza dair kısa açıklamalar.",
        keys: [
          "imm.lvl_eyebrow",
          "imm.lvl_title",
          "imm.lvl_note",
          "imm.lvl_daily",
          "imm.lvl_now",
          "imm.lvl_a1",
          "imm.lvl_a2",
          "imm.lvl_b1",
          "imm.lvl_b2",
          "imm.lvl_c1",
          "imm.lvl_c2",
        ],
      },
      {
        title: "Ders süreleri",
        keys: [
          "lessons.durationsTitle",
          "lessons.min15",
          "lessons.min15Desc",
          "lessons.min30",
          "lessons.min30Desc",
          "lessons.min60",
          "lessons.min60Desc",
          "lessons.cta",
        ],
      },
      {
        title: "Ders dönüşüm bölümü (rezervasyon çağrısı)",
        keys: [
          "convert.lesBook",
          "convert.lesCapacity",
          "convert.lesPopular",
          "convert.lesReassure",
          "convert.lesPick",
        ],
      },
      {
        title: "PetLingo uygulaması",
        help: "Kendi dil uygulamanızın tanıtımı ve özellikleri.",
        keys: [
          "imm.pl_eyebrow",
          "imm.pl_title",
          "imm.pl_desc",
          "imm.pl_ai",
          "imm.pl_f1",
          "imm.pl_f2",
          "imm.pl_f3",
          "imm.pl_f4",
          "imm.pl_f5",
          "imm.pl_f6",
          "imm.pl_cta",
          "imm.pl_soon",
          "imm.pl_combo",
          "imm.pl_own",
        ],
      },
      {
        title: "Türkçe kelime yapbozu (oyun)",
        keys: [
          "imm.les_puzzleEyebrow",
          "imm.les_puzzleTitle",
          "imm.les_puzzleDesc",
          "imm.les_puzzleMeaning",
          "imm.les_puzzleNext",
          "imm.les_puzzleShuffle",
          "imm.les_puzzleDone",
          "imm.les_puzzleAllDone",
          "imm.les_puzzleRestart",
          "imm.les_puzzleProgress",
          "imm.les_m_deniz",
          "imm.les_m_gunes",
          "imm.les_m_cay",
          "imm.les_m_kahve",
          "imm.les_m_kale",
          "imm.les_m_liman",
        ],
      },
      {
        title: "Randevu / rezervasyon formu",
        keys: [
          "booking.title",
          "booking.intro",
          "convert.orDirect",
          "convert.lesMsg",
          "booking.pickSlot",
          "booking.noSlots",
          "booking.name",
          "booking.email",
          "booking.phone",
          "booking.note",
          "booking.submit",
          "booking.success",
          "booking.taken",
          "booking.error",
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "education",
    label: "Eğitim",
    description: "Türkiye'de eğitim danışmanlığı sayfası — yolculuk adımları ve güvence.",
    sections: [
      {
        title: "Hero / üst bölüm",
        keys: ["education.title", "education.intro"],
      },
      {
        title: "Öne çıkanlar (özellikler)",
        keys: [
          "education.feature1",
          "education.feature2",
          "education.feature3",
          "education.feature4",
          "education.cta",
        ],
      },
      {
        title: "Eğitim yolculuğu — adımlar (6 adım)",
        help: "Program seçimi → başvuru & burs → kabul mektubu → belgeler & geliş → yurt & öğrenci hayatı → mezuniyet & yeni hayat.",
        keys: [
          "imm.edu_journeyEyebrow",
          "imm.edu_weDo",
          "imm.edu_s1Title",
          "imm.edu_s1Place",
          "imm.edu_s1Text",
          "imm.edu_s1a",
          "imm.edu_s1b",
          "imm.edu_s1We",
          "imm.edu_s2Title",
          "imm.edu_s2Place",
          "imm.edu_s2Text",
          "imm.edu_s2a",
          "imm.edu_s2b",
          "imm.edu_s2We",
          "imm.edu_s5Title",
          "imm.edu_s5Place",
          "imm.edu_s5Text",
          "imm.edu_s5a",
          "imm.edu_s5b",
          "imm.edu_s5We",
          "imm.edu_s3Title",
          "imm.edu_s3Place",
          "imm.edu_s3Text",
          "imm.edu_s3a",
          "imm.edu_s3b",
          "imm.edu_s3We",
          "imm.edu_s4Title",
          "imm.edu_s4Place",
          "imm.edu_s4Text",
          "imm.edu_s4a",
          "imm.edu_s4b",
          "imm.edu_s4We",
          "imm.edu_s6Title",
          "imm.edu_s6Place",
          "imm.edu_s6Text",
          "imm.edu_s6a",
          "imm.edu_s6b",
          "imm.edu_s6We",
        ],
      },
      {
        title: "Kampüste yürü (360° sokak)",
        keys: ["imm.edu_streetEyebrow", "imm.edu_streetTitle", "imm.edu_streetIntro"],
      },
      {
        title: "Eğitim dönüşüm bölümü (ne hallediyoruz)",
        keys: [
          "convert.eduDeliverTitle",
          "convert.eduDeliverText",
          "convert.eduUrgency",
          "convert.eduCta",
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "about",
    label: "Hakkımızda",
    description: "Hakkımızda sayfası — hikaye, zaman çizelgesi, değerler ve hizmet alanları.",
    sections: [
      {
        title: "Hero / giriş",
        keys: ["about.title", "about.body"],
      },
      {
        title: "Hikayemiz",
        keys: [
          "imm.ab_eyebrow",
          "imm.ab_story1Title",
          "imm.ab_story1Text",
          "imm.ab_story2Title",
          "imm.ab_story2Text",
        ],
      },
      {
        title: "Zaman çizelgesi (hikayemiz adım adım)",
        keys: [
          "convert.aboutTimelineTitle",
          "convert.tl1T",
          "convert.tl1X",
          "convert.tl2T",
          "convert.tl2X",
          "convert.tl3T",
          "convert.tl3X",
          "convert.tl4T",
          "convert.tl4X",
          "convert.tl5T",
          "convert.tl5X",
          "convert.founderEng",
          "convert.founderTeacher",
          "convert.coupleCaption",
          "convert.coupleRep",
        ],
      },
      {
        title: "Bizi farklı kılan (değerler)",
        keys: [
          "imm.ab_valuesTitle",
          "imm.ab_v1Title",
          "imm.ab_v1Text",
          "imm.ab_v2Title",
          "imm.ab_v2Text",
          "imm.ab_v3Title",
          "imm.ab_v3Text",
        ],
      },
      {
        title: "Yaşanmış tecrübe / kanıt",
        keys: [
          "convert.aboutProofTitle",
          "imm.lived_badge",
          "imm.lived_title",
          "imm.lived_text",
          "imm.lived_cta",
        ],
      },
      {
        title: "Hizmet alanları",
        help: "Hakkımızda sayfasında listelenen hizmet kartları (Antalya, ders, eğitim, IT).",
        keys: [
          "convert.aboutServicesTitle",
          "services.antalyaTitle",
          "services.antalyaDesc",
          "services.lessonsTitle",
          "services.lessonsDesc",
          "services.educationTitle",
          "services.educationDesc",
          "services.itTitle",
          "services.itDesc",
          "services.it_eyebrow",
          "services.it_lead",
          "services.it_f1",
          "services.it_f2",
          "services.it_f3",
          "services.it_f4",
          "services.it_cta",
        ],
      },
      {
        title: "Kapanış / sıradaki adım",
        keys: ["convert.aboutNextTitle", "convert.aboutNextText"],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "faq",
    label: "SSS",
    description: "Sıkça sorulan sorular sayfası.",
    sections: [
      {
        title: "Hero / başlık",
        keys: ["imm.faq_eyebrow", "faq.title"],
      },
      {
        title: "Sorular & cevaplar",
        keys: [
          "faq.q1",
          "faq.a1",
          "faq.q2",
          "faq.a2",
          "faq.q3",
          "faq.a3",
          "faq.q4",
          "faq.a4",
          "faq.q5",
          "faq.a5",
          "faq.q6",
          "faq.a6",
          "faq.q7",
          "faq.a7",
          "faq.q8",
          "faq.a8",
          "faq.q9",
          "faq.a9",
          "faq.q10",
          "faq.a10",
          "faq.q11",
          "faq.a11",
          "faq.q12",
          "faq.a12",
          "faq.q13",
          "faq.a13",
          "faq.q14",
          "faq.a14",
          "faq.q15",
          "faq.a15",
          "faq.q16",
          "faq.a16",
        ],
      },
      {
        title: "Kapanış CTA",
        keys: ["convert.faqCtaTitle", "convert.faqCtaText", "convert.whatsapp", "convert.telegram", "convert.emailWrite"],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "contact",
    label: "İletişim",
    description: "İletişim sayfası — form, ödeme yöntemleri ve konum.",
    sections: [
      {
        title: "Hero / üst bölüm",
        keys: ["contact.orReach", "contact.title", "contact.subtitle"],
      },
      {
        title: "Güvence şeridi",
        keys: [
          "convert.conAssure1",
          "convert.conAssure2",
          "convert.conAssure3",
          "convert.conQuick",
          "convert.conQuickText",
        ],
      },
      {
        title: "İletişim formu",
        keys: [
          "contact.name",
          "contact.email",
          "contact.phone",
          "contact.service",
          "contact.serviceAntalya",
          "contact.serviceLessons",
          "contact.serviceEducation",
          "contact.serviceOther",
          "contact.message",
          "contact.submit",
          "contact.success",
          "contact.error",
        ],
      },
      {
        title: "Ödeme yöntemleri",
        keys: [
          "payment.title",
          "payment.kaspiTitle",
          "payment.kaspiText",
          "payment.cryptoTitle",
          "payment.cryptoText",
          "payment.note",
          "payment.verifyWarning",
          "payment.networkLabel",
          "payment.empty",
          "payment.txidNote",
        ],
      },
      {
        title: "Bizi Antalya'da bul (konum)",
        keys: ["imm.con_findTitle", "imm.con_findText"],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    id: "genel",
    label: "Genel (menü & ortak)",
    description: "Menü, site adı, ortak butonlar ve site geneli metinler.",
    sections: [
      {
        title: "Site kimliği / SEO",
        keys: ["meta.siteName", "meta.tagline", "meta.description"],
      },
      {
        title: "Menü (navigasyon)",
        keys: [
          "nav.home",
          "nav.antalya",
          "nav.lessons",
          "nav.education",
          "nav.about",
          "nav.faq",
          "nav.contact",
        ],
      },
      {
        title: "Alt bilgi (footer)",
        keys: [
          "footer.rights",
          "footer.follow",
          "footer.quickLinks",
          "footer.services",
          "footer.contact",
        ],
      },
      {
        title: "Ortak butonlar & etiketler",
        keys: [
          "common.learnMore",
          "common.getStarted",
          "common.contactUs",
          "common.bookNow",
          "common.send",
          "common.loading",
          "common.lightMode",
          "common.darkMode",
          "common.language",
          "common.from",
          "common.errorTitle",
          "common.errorText",
          "common.errorRetry",
        ],
      },
      {
        title: "Genel satış mesajı (sana özel)",
        help: "Farklı sayfalarda kullanılan 'paket değil, sana özel' vurgusu.",
        keys: [
          "imm.sell_eyebrow",
          "imm.sell_title",
          "imm.sell_text",
          "imm.sell_b1",
          "imm.sell_b2",
          "imm.sell_b3",
          "imm.sell_cta",
        ],
      },
      {
        title: "Kripto ödeme sayfası (checkout)",
        help: "Kripto ödeme akışındaki durum ekranları ve mesajlar.",
        keys: [
          "checkout.title",
          "checkout.ref",
          "checkout.amount",
          "checkout.discount",
          "checkout.toPay",
          "checkout.payButton",
          "checkout.networks",
          "checkout.waiting",
          "checkout.paidTitle",
          "checkout.paidBody",
          "checkout.expiredTitle",
          "checkout.expiredBody",
          "checkout.cancelledTitle",
          "checkout.failedTitle",
          "checkout.failedBody",
          "checkout.underpaidTitle",
          "checkout.underpaidBody",
          "checkout.notFound",
          "checkout.secured",
        ],
      },
    ],
  },
];
