/**
 * TÜRKÇE İKON ARAMA — turizm/danışmanlık bağlamında sık aranan Türkçe terimleri
 * Font Awesome ikon adlarının parçalarına (fragment) eşler. İkon seçici (client)
 * bu tabloyu kullanır: kullanıcı "tekne" yazınca "ship" / "sailboat" içeren FA
 * adları da eşleşir. Değerler FA ikon adının (iconName, ör. "person-swimming")
 * içinde substring olarak aranır — birebir ad değil, parça yeter.
 *
 * Not: Anahtarlar küçük harf + Türkçe locale ile normalize edilmiş aranır
 * (İ/ı/ş/ç... duyarsız değil ama kullanıcı doğal yazınca eşleşir).
 */
export const TR_ICON_ALIASES: Record<string, string[]> = {
  // Ulaşım
  ucak: ["plane"],
  uçak: ["plane"],
  ucus: ["plane"],
  uçuş: ["plane"],
  transfer: ["car", "van", "shuttle"],
  araba: ["car"],
  araç: ["car"],
  otobus: ["bus"],
  otobüs: ["bus"],
  tren: ["train"],
  taksi: ["taxi", "car"],
  tekne: ["ship", "sailboat", "ferry", "anchor"],
  yat: ["sailboat", "ship", "anchor"],
  gemi: ["ship", "ferry"],
  vapur: ["ferry", "ship"],
  bisiklet: ["bicycle", "bicycle"],
  motosiklet: ["motorcycle"],
  yuruyus: ["person-walking", "person-hiking", "shoe-prints"],
  yürüyüş: ["person-walking", "person-hiking", "shoe-prints"],
  teleferik: ["cable-car", "gondola", "tram"],
  balon: ["fire", "wind"],
  helikopter: ["helicopter"],
  pasaport: ["passport"],
  bilet: ["ticket"],
  bavul: ["suitcase", "suitcase-rolling"],
  valiz: ["suitcase", "suitcase-rolling"],
  harita: ["map", "map-location", "location-dot"],
  konum: ["location-dot", "map-pin", "map-location"],
  pusula: ["compass"],
  yon: ["signs-post", "compass"],
  yön: ["signs-post", "compass"],

  // Konaklama
  otel: ["hotel", "bed", "building"],
  konaklama: ["bed", "hotel"],
  yatak: ["bed"],
  oda: ["bed", "door-closed"],
  anahtar: ["key"],
  resepsiyon: ["bell-concierge", "concierge-bell"],
  villa: ["house", "house-chimney"],
  ev: ["house"],
  cadir: ["tent", "campground"],
  çadır: ["tent", "campground"],
  kamp: ["campground", "tent", "fire"],
  yildiz: ["star"],
  yıldız: ["star"],

  // Yeme-içme
  yemek: ["utensils", "bowl-food", "plate-wheat"],
  restoran: ["utensils", "bowl-food"],
  kahvalti: ["mug-saucer", "egg", "utensils"],
  kahvaltı: ["mug-saucer", "egg", "utensils"],
  kahve: ["mug-hot", "mug-saucer", "coffee"],
  cay: ["mug-hot"],
  çay: ["mug-hot"],
  icecek: ["martini-glass", "wine-glass", "champagne-glasses"],
  içecek: ["martini-glass", "wine-glass", "champagne-glasses"],
  sarap: ["wine-glass", "wine-bottle"],
  şarap: ["wine-glass", "wine-bottle"],
  bar: ["martini-glass", "wine-glass"],
  pizza: ["pizza-slice"],
  balik: ["fish"],
  balık: ["fish"],
  meyve: ["apple-whole", "lemon"],
  pasta: ["cake-candles", "birthday-cake"],
  dondurma: ["ice-cream"],

  // Doğa / deniz / manzara
  deniz: ["water", "umbrella-beach", "sailboat"],
  plaj: ["umbrella-beach"],
  kumsal: ["umbrella-beach"],
  gunes: ["sun", "umbrella-beach"],
  güneş: ["sun", "umbrella-beach"],
  gunbatimi: ["sun"],
  günbatımı: ["sun"],
  su: ["water", "droplet"],
  dalga: ["water"],
  sortu: ["water"],
  havuz: ["water-ladder", "person-swimming"],
  yuzme: ["person-swimming"],
  yüzme: ["person-swimming"],
  dalis: ["person-swimming", "water", "fish"],
  dalış: ["person-swimming", "water", "fish"],
  sorf: ["water"],
  sörf: ["water"],
  dag: ["mountain", "mountain-sun"],
  dağ: ["mountain", "mountain-sun"],
  tepe: ["mountain", "mountain-sun"],
  orman: ["tree", "tree-city"],
  agac: ["tree"],
  ağaç: ["tree"],
  cicek: ["spa", "seedling", "leaf"],
  çiçek: ["spa", "seedling", "leaf"],
  yaprak: ["leaf"],
  kanyon: ["mountain"],
  magara: ["mountain"],
  mağara: ["mountain"],
  selale: ["water", "droplet"],
  şelale: ["water", "droplet"],
  gol: ["water"],
  göl: ["water"],
  nehir: ["water"],
  ada: ["umbrella-beach"],
  kus: ["dove", "crow", "feather"],
  kuş: ["dove", "crow", "feather"],
  hayvan: ["paw", "hippo", "dog", "cat"],
  at: ["horse", "horse-head"],

  // Tarih / kültür / gezi
  muze: ["landmark", "building-columns"],
  müze: ["landmark", "building-columns"],
  kale: ["chess-rook", "fort-awesome", "tower-observation"],
  antik: ["landmark", "building-columns"],
  tarih: ["landmark", "building-columns", "book"],
  cami: ["mosque"],
  kilise: ["church"],
  tapinak: ["gopuram", "landmark"],
  tapınak: ["gopuram", "landmark"],
  heykel: ["monument", "landmark"],
  saray: ["landmark", "building-columns"],
  kule: ["tower-observation", "tower-cell"],
  koru: ["tree"],
  pazar: ["basket-shopping", "store", "shop"],
  carsi: ["basket-shopping", "store", "shop"],
  çarşı: ["basket-shopping", "store", "shop"],
  alisveris: ["bag-shopping", "basket-shopping", "cart-shopping"],
  alışveriş: ["bag-shopping", "basket-shopping", "cart-shopping"],
  hediye: ["gift"],
  fotograf: ["camera", "image"],
  fotoğraf: ["camera", "image"],
  kamera: ["camera", "video"],
  rehber: ["person-chalkboard", "map", "book"],
  bayrak: ["flag", "flag-checkered"],

  // Sağlık / keyif
  spa: ["spa", "hot-tub-person"],
  masaj: ["hands", "spa"],
  hamam: ["hot-tub-person", "spa"],
  saglik: ["heart-pulse", "hand-holding-medical", "kit-medical"],
  sağlık: ["heart-pulse", "hand-holding-medical", "kit-medical"],
  kalp: ["heart"],
  askk: ["heart"],
  ask: ["heart"],
  aşk: ["heart"],
  balayi: ["heart", "champagne-glasses"],
  balayı: ["heart", "champagne-glasses"],
  romantik: ["heart", "champagne-glasses"],
  aile: ["people-roof", "children", "person-breastfeeding"],
  cocuk: ["child", "children", "baby"],
  çocuk: ["child", "children", "baby"],
  eglence: ["ferris-wheel", "masks-theater", "music"],
  eğlence: ["ferris-wheel", "masks-theater", "music"],
  luna: ["ferris-wheel"],
  muzik: ["music"],
  müzik: ["music"],
  spor: ["dumbbell", "futbol", "person-running"],
  golf: ["golf-ball-tee"],
  futbol: ["futbol"],

  // Destek / iletişim / süreç
  destek: ["headset", "life-ring", "hands-holding"],
  iletisim: ["phone", "envelope", "comments"],
  iletişim: ["phone", "envelope", "comments"],
  telefon: ["phone", "mobile"],
  whatsapp: ["comment", "comments", "phone"],
  mesaj: ["comment", "comments", "envelope"],
  mail: ["envelope"],
  eposta: ["envelope"],
  takvim: ["calendar", "calendar-days"],
  gun: ["calendar-day", "sun"],
  gün: ["calendar-day", "sun"],
  saat: ["clock"],
  zaman: ["clock", "hourglass"],
  para: ["money-bill", "coins", "wallet"],
  odeme: ["credit-card", "money-bill", "wallet"],
  ödeme: ["credit-card", "money-bill", "wallet"],
  kredikarti: ["credit-card"],
  fiyat: ["tag", "money-bill"],
  indirim: ["percent", "tag"],
  guvenlik: ["shield-halved", "lock"],
  güvenlik: ["shield-halved", "lock"],
  onay: ["check", "circle-check"],
  yildizli: ["star"],
  bilgi: ["circle-info", "info"],
  soru: ["circle-question"],
  uyari: ["triangle-exclamation"],
  uyarı: ["triangle-exclamation"],
  dahil: ["check", "circle-check"],
  liste: ["list", "list-check"],
};

/** Türkçe/serbest metni FA ad-fragment listesine çözer (eşleşme yoksa []). */
export function trAliasFragments(query: string): string[] {
  const q = query.trim().toLocaleLowerCase("tr");
  if (!q) return [];
  const out = new Set<string>();
  for (const [alias, frags] of Object.entries(TR_ICON_ALIASES)) {
    if (alias.includes(q) || q.includes(alias)) frags.forEach((f) => out.add(f));
  }
  return [...out];
}
